version: '3.8'

services:
  flask_server:
    image: ${DOCKERHUB_USERNAME}/scanwebsite:flask_server-${COMMIT_HASH}
    container_name: flask_server
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
    entrypoint: ["./dockerize", "-wait=tcp://client:8080", "-timeout=60s", "--", "flask", "run", "--host=0.0.0.0", "--port=5000"]
    ports:
      - "5000:5000"
    networks:
      - app_network

  client:
    image: ${DOCKERHUB_USERNAME}/scanwebsite:client-${COMMIT_HASH}
    container_name: client
    entrypoint: ["./dockerize", "-wait=tcp://flask_server:5000", "-timeout=60s", "--", "nginx", "-g", "daemon off;"]
    ports:
      - "8080:80"
    depends_on:
      - flask_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
