version: "3.8"

services:
  flask_server:
    build: 
      context: ./website/flask_server
      dockerfile: Dockerfile
    container_name: flask_server
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    networks:
      - app_network

  client:
    build:
      context: ./website/client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "8080:80"
    depends_on:
      - flask_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
