version: "3.8"

services:
  flask_server:
    image: ${DOCKERHUB_USERNAME}/scanwebsite:flask_server-${COMMIT_HASH}
    container_name: flask_server
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    networks:
      - app_network
    # L'entrée du serveur Flask avec Gunicorn est déjà définie dans le Dockerfile, donc l'entrypoint ne doit pas inclure de dockerize ici.
    entrypoint: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "server:app"]

  client:
    image: ${DOCKERHUB_USERNAME}/scanwebsite:client-${COMMIT_HASH}
    container_name: client
    entrypoint: ["dockerize", "-wait=tcp://flask_server:5000", "-timeout=60s", "--", "nginx", "-g", "daemon off;"]
    ports:
      - "8080:80"
    depends_on:
      - flask_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
