version: "3.8"

services:
  flask_server:
    image: ${DOCKERHUB_USERNAME}/scanwebsite:flask_server-${COMMIT_HASH}
    container_name: flask_server
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
    # L'entrypoint attend que le service 'client' soit prêt avant de démarrer Flask
    entrypoint: >
      sh -c "until nc -z client 80; do echo waiting for client; sleep 2; done;
      flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    networks:
      - app_network

  client:
    image: ${DOCKERHUB_USERNAME}/scanwebsite:client-${COMMIT_HASH}
    container_name: client
    entrypoint: >
      sh -c "until nc -z flask_server 5000; do echo waiting for flask_server; sleep 2; done;
      nginx -g 'daemon off;'"
    ports:
      - "8080:80"
    depends_on:
      - flask_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
