version: "3.8"

services:
  flask_server:
    image: ${DOCKERHUB_USERNAME}/scanwebsite:flask_server-${COMMIT_HASH}
    container_name: flask_server
    mem_limit: 512M
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
    # entrypoint: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    ports:
      - "5000:5000"
    networks:
      - app_network

  client:
    image: ${DOCKERHUB_USERNAME}/scanwebsite:client-${COMMIT_HASH}
    container_name: client
    mem_limit: 512M
    # On remplace l'entrypoint pour faire un check sur le serveur Flask avant de démarrer NGINX
    entrypoint: >
      sh -c "until nc -z flask_server 5000; do echo waiting for flask_server; sleep 2; done;
      nginx -g 'daemon off;'"
    ports:
      - "8080:80"
    depends_on:
      - flask_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
